package gui;

import javax.swing.JOptionPane;
import service.alunos.Alunos;
import service.alunos.AlunosFormValidation;
import service.constants.Constants;

/**
 *
 * @author LucasDias
 */
public class CadastroAlunos extends javax.swing.JFrame {

    /**
     * Creates new form cadastroAlunos
     */
    public CadastroAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroAlunosTitulo = new javax.swing.JLabel();
        cadastroAlunosNome = new javax.swing.JTextField();
        cadastroAlunosCurso = new javax.swing.JComboBox<>();
        cadastroAlunosTelefone = new javax.swing.JTextField();
        cadastroAlunosMatricula = new javax.swing.JComboBox<>();
        cadastroAlunosSalvar = new javax.swing.JButton();
        cadastroAlunosCancelar = new javax.swing.JButton();
        cadastroAlunosLabelTelefone = new javax.swing.JLabel();
        cadastroAlunosLabelNome = new javax.swing.JLabel();

        setResizable(false);

        cadastroAlunosTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cadastroAlunosTitulo.setText("Cadastro de alunos");

        cadastroAlunosNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cadastroAlunosNomeFocusLost(evt);
            }
        });
        cadastroAlunosNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroAlunosNomeMouseClicked(evt);
            }
        });
        cadastroAlunosNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunosNomeActionPerformed(evt);
            }
        });

        cadastroAlunosCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Curso...", "Informática", "Inglês", "Espanhol", "Alemão" }));
        cadastroAlunosCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunosCursoActionPerformed(evt);
            }
        });

        cadastroAlunosTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunosTelefoneActionPerformed(evt);
            }
        });

        cadastroAlunosMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matrícula...", "Ativa", "Inativa" }));

        cadastroAlunosSalvar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LucasDias\\Desktop\\StudentRegistration\\src\\main\\images\\iconfinder_Yes_132693.png")); // NOI18N
        cadastroAlunosSalvar.setText("Salvar");
        cadastroAlunosSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunosSalvarActionPerformed(evt);
            }
        });

        cadastroAlunosCancelar.setText("Cancelar");
        cadastroAlunosCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunosCancelarActionPerformed(evt);
            }
        });

        cadastroAlunosLabelTelefone.setText("Telefone");

        cadastroAlunosLabelNome.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroAlunosCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastroAlunosTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastroAlunosSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastroAlunosCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addComponent(cadastroAlunosMatricula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastroAlunosLabelTelefone)
                            .addComponent(cadastroAlunosLabelNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastroAlunosNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cadastroAlunosTelefone))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroAlunosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroAlunosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroAlunosMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroAlunosNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroAlunosLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroAlunosTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroAlunosLabelTelefone))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadastroAlunosCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cadastroAlunosSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroAlunosTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunosTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroAlunosTelefoneActionPerformed

    private void cadastroAlunosCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunosCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cadastroAlunosCancelarActionPerformed

    private void cadastroAlunosCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunosCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroAlunosCursoActionPerformed

    private void cadastroAlunosNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroAlunosNomeMouseClicked
  // TODO add your handling code here:
    }//GEN-LAST:event_cadastroAlunosNomeMouseClicked

    private void cadastroAlunosNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadastroAlunosNomeFocusLost

    }//GEN-LAST:event_cadastroAlunosNomeFocusLost

    private void cadastroAlunosSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunosSalvarActionPerformed
        AlunosFormValidation validacaoFormulario = new AlunosFormValidation();

        if (!validacaoFormulario.validarNome(cadastroAlunosNome.getText())
                || !validacaoFormulario.validarCurso(cadastroAlunosCurso.getSelectedItem().toString())
                || !validacaoFormulario.validarMatricula(cadastroAlunosMatricula.getSelectedItem().toString())
                || !validacaoFormulario.validarTelefone(Integer.parseInt(cadastroAlunosTelefone.getText()))) {
            JOptionPane.showMessageDialog(null, Constants.ALL_FIELDS_MUST_BE_FILLED);
        } else {
            Alunos aluno = new Alunos(
                    cadastroAlunosNome.getText(),
                    cadastroAlunosCurso.getSelectedItem().toString(),
                    cadastroAlunosMatricula.getSelectedItem().toString(),
                    Integer.parseInt(cadastroAlunosTelefone.getText()));

            JOptionPane.showMessageDialog(null,
                    Constants.ALUNOS_THE_STUDENT
                    + aluno.getNome()
                    + Constants.ALUNOS_WAS_SAVED);
        }
    }//GEN-LAST:event_cadastroAlunosSalvarActionPerformed

    private void cadastroAlunosNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunosNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroAlunosNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroAlunosCancelar;
    private javax.swing.JComboBox<String> cadastroAlunosCurso;
    private javax.swing.JLabel cadastroAlunosLabelNome;
    private javax.swing.JLabel cadastroAlunosLabelTelefone;
    private javax.swing.JComboBox<String> cadastroAlunosMatricula;
    private javax.swing.JTextField cadastroAlunosNome;
    private javax.swing.JButton cadastroAlunosSalvar;
    private javax.swing.JTextField cadastroAlunosTelefone;
    private javax.swing.JLabel cadastroAlunosTitulo;
    // End of variables declaration//GEN-END:variables
}
