/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author LucasDias
 */
public class CadastroAlunos extends javax.swing.JFrame {

    /**
     * Creates new form cadastroAlunos
     */
    public CadastroAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroAlunosTitulo = new javax.swing.JLabel();
        cadastroAlunosNome = new javax.swing.JTextField();
        cadastroAlunosCurso = new javax.swing.JComboBox<>();
        cadastroAlunosTelefone = new javax.swing.JTextField();
        cadastroAlunosMatricula = new javax.swing.JComboBox<>();
        cadastroAlunosSalvar = new javax.swing.JButton();
        cadastroAlunosCancelar = new javax.swing.JButton();

        setResizable(false);

        cadastroAlunosTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cadastroAlunosTitulo.setText("Cadastro de alunos");

        cadastroAlunosNome.setText("Nome");

        cadastroAlunosCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Curso...", "Informática", "Inglês", "Espanhol", "Alemão" }));
        cadastroAlunosCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunosCursoActionPerformed(evt);
            }
        });

        cadastroAlunosTelefone.setText("(00) 00000-0000");
        cadastroAlunosTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunosTelefoneActionPerformed(evt);
            }
        });

        cadastroAlunosMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Situação da matrícula...", "Ativa", "Inativa" }));

        cadastroAlunosSalvar.setIcon(new javax.swing.ImageIcon("C:\\Users\\LucasDias\\Desktop\\StudentRegistration\\src\\main\\images\\iconfinder_Yes_132693.png")); // NOI18N
        cadastroAlunosSalvar.setText("Salvar");

        cadastroAlunosCancelar.setText("Cancelar");
        cadastroAlunosCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunosCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroAlunosNome)
                    .addComponent(cadastroAlunosCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroAlunosTelefone)
                    .addComponent(cadastroAlunosMatricula, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastroAlunosTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadastroAlunosSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cadastroAlunosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroAlunosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroAlunosNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroAlunosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroAlunosTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroAlunosMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroAlunosSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroAlunosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroAlunosTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunosTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroAlunosTelefoneActionPerformed

    private void cadastroAlunosCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunosCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cadastroAlunosCancelarActionPerformed

    private void cadastroAlunosCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunosCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroAlunosCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroAlunosCancelar;
    private javax.swing.JComboBox<String> cadastroAlunosCurso;
    private javax.swing.JComboBox<String> cadastroAlunosMatricula;
    private javax.swing.JTextField cadastroAlunosNome;
    private javax.swing.JButton cadastroAlunosSalvar;
    private javax.swing.JTextField cadastroAlunosTelefone;
    private javax.swing.JLabel cadastroAlunosTitulo;
    // End of variables declaration//GEN-END:variables
}
