package gui;

/**
 *
 * @author LucasDias
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaInicialTitulo = new javax.swing.JLabel();
        telaInicialJScrollPane = new javax.swing.JScrollPane();
        telaInicialTabela = new javax.swing.JTable();
        telaInicialBotaoEditar = new javax.swing.JButton();
        telaInicialBotaoRemover = new javax.swing.JButton();
        telaInicialMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Alunos e Cursos");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.darkGray);
        setName("telaInicial"); // NOI18N
        setResizable(false);

        telaInicialTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        telaInicialTitulo.setText("Lista de alunos");
        telaInicialTitulo.setFocusable(false);
        telaInicialTitulo.setName("tituloTelaInicial"); // NOI18N

        telaInicialTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do aluno", "Telefone para contato", "Curso", "Status da matrícula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        telaInicialTabela.setName("telaInicialTabela"); // NOI18N
        telaInicialJScrollPane.setViewportView(telaInicialTabela);

        telaInicialBotaoEditar.setText("Editar");

        telaInicialBotaoRemover.setText("Remover");

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LucasDias\\Desktop\\StudentRegistration\\src\\main\\images\\iconfinder_List_132709.png")); // NOI18N
        jMenu1.setText("Cadastro");
        jMenu1.setName("menuItemCadastro"); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LucasDias\\Desktop\\StudentRegistration\\src\\main\\images\\iconfinder_Boss_132688.png")); // NOI18N
        jMenuItem1.setText("Alunos");
        jMenuItem1.setMaximumSize(new java.awt.Dimension(320, 320));
        jMenuItem1.setName("itemAlunos"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LucasDias\\Desktop\\StudentRegistration\\src\\main\\images\\iconfinder_Notes_132689.png")); // NOI18N
        jMenuItem2.setText("Cursos");
        jMenuItem2.setName("itemCursos"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        telaInicialMenuBar.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LucasDias\\Desktop\\StudentRegistration\\src\\main\\images\\iconfinder_About_132628.png")); // NOI18N
        jMenu2.setText("Ajuda");
        jMenu2.setName("menuItemAjuda"); // NOI18N
        telaInicialMenuBar.add(jMenu2);

        setJMenuBar(telaInicialMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telaInicialTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telaInicialBotaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telaInicialBotaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(telaInicialJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telaInicialTitulo)
                    .addComponent(telaInicialBotaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(telaInicialBotaoRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telaInicialJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        telaInicialTitulo.getAccessibleContext().setAccessibleName("tituloTelaInicial");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroAlunos cadastroAlunos = new CadastroAlunos();
        cadastroAlunos.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CadastroCursos cadastroCursos = new CadastroCursos();
        cadastroCursos.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton telaInicialBotaoEditar;
    private javax.swing.JButton telaInicialBotaoRemover;
    private javax.swing.JScrollPane telaInicialJScrollPane;
    private javax.swing.JMenuBar telaInicialMenuBar;
    private javax.swing.JTable telaInicialTabela;
    private javax.swing.JLabel telaInicialTitulo;
    // End of variables declaration//GEN-END:variables
}
